name: example
description: Demonstrates how to use the logger_flutter plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger_flutter:
    path: ../

flutter:
  uses-material-design: true