name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.1-nullsafety.0
homepage: https://github.com/HeyLor/logger_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.1.0
  sensors_plus: ^4.0.2
